= Using Functions for GraphQL Service Invocations

:graphql_schema_url: https://graphql.org/learn/schema/

If you want to use GraphQL services, you can also invoke them using a similar syntax to the above methods.

We'll use the following link:{graphql_schema_url}[GraphQL schema definition] to show how that would work with both a query and a mutation:

[source,graphql]
----
type Query {
    pets: [Pet]
    pet(id: Int!): Pet
}

type Mutation {
    createPet(pet: PetInput!): Pet
}

type Treat {
    id: Int!
}

type Pet {
    id: Int!
    name: String!
    favoriteTreat: Treat
}

input PetInput {
    id: Int!
    name: String!
    favoriteTreatId: Int
}
----

== Invoking a GraphQL Query

In our workflow definition, we can then use a function definition for the `pet` query field as such:

[source,json]
----
{
  "functions": [
    {
      "name": "getOnePet",
      "operation": "https://example.com/pets/graphql#query#pet",
      "type": "graphql"
    }
  ]
}
----

Note that the `operation` property has the following format for the `graphql` type:

[source]
----
<url_to_graphql_endpoint>#<literal "mutation" or "query">#<mutation_or_query_field>
----

In order to invoke this query, we would use the following `functionRef` parameters:

[source,json]
----
{
  "refName": "getOnePet",
  "arguments": {
    "id": 42
  },
  "selectionSet": "{ id, name, favoriteTreat { id } }"
}
----

Which would return the following result:

[source,json]
----
{
  "pet": {
    "id": 42,
    "name": "Snuffles",
    "favoriteTreat": {
      "id": 9001
    }
  }
}
----

== Invoking a GraphQL Mutation

Likewise, we would use the following function definition:

[source,json]
----
{
  "functions": [
    {
      "name": "createPet",
      "operation": "https://example.com/pets/graphql#mutation#createPet",
      "type": "graphql"
    }
  ]
}
----

With the parameters for the `functionRef`:

[source,json]
----
{
  "refName": "createPet",
  "arguments": {
    "pet": {
      "id": 43,
      "name":"Sadaharu",
      "favoriteTreatId": 9001
    }
  },
  "selectionSet": "{ id, name, favoriteTreat { id } }"
}
----

Which would execute the mutation, creating the object and returning the following data:

[source,json]
----
{
  "pet": {
    "id": 43,
    "name": "Sadaharu",
    "favoriteTreat": {
      "id": 9001
    }
  }
}
----

Note you can include xref:spec/workflow_expressions.adoc[expressions] in both `arguments` and `selectionSet`:

[source,json]
----
{
  "refName": "getOnePet",
  "arguments": {
    "id": "${ .petId }"
  },
  "selectionSet": "{ id, name, age(useDogYears: ${ .isPetADog }) { dateOfBirth, years } }"
}v
----

Expressions must be evaluated before executing the operation.

Note that GraphQL Subscriptions are not supported at this time.

For more information about functions, reference the xref:spec/structure/state_definitions/function.adoc[Function Definition] section.
