= FunctionRef Definition

`FunctionRef` definition can have two types, either `string` or `object`. If `string` type, it defines the name of the referenced xref:spec/structure/state_definitions/function.adoc[function]. This can be used as a short-cut definition when you don't need to define any other parameters, for example:

[source,json]
----
"functionRef": "myFunction"
----

Note that if used with `string` type, the invocation of the function is synchronous.

If you need to define parameters in your `functionRef` definition, you can define it with its `object` type which has the following properties:

[cols="1,3,1,1"]
|===
|Parameter  |Description |Type |Required

|refName
|Name of the referenced xref:spec/structure/state_definitions/function.adoc[function]
|string
|yes

|arguments	
|Arguments (inputs) to be passed to the referenced function	
|object
|yes if function type is `graphql`, otherwise no

|selectionSet	
|Used if function type is graphql. String containing a valid GraphQL link:{graphql_spec_url}#sec-Selection-Sets[selection set]
|string	
|yes if function type is `graphql`, otherwise no

|invoke
|Specifies if the function should be invoked sync or async. Default is sync	
|string
|no

|===

[tabs]
====
YAML::
+
--
[source,yaml]
----
refName: finalizeApplicationFunction
arguments:
  applicantid: "${ .applicantId }"
----
--
JSON::
+
--
[source,json]
----
{
    "refName": "finalizeApplicationFunction",
    "arguments": {
        "applicantid": "${ .applicantId }"
    }
}
----
--
====

The `refName` property is the name of the referenced xref:spec/structure/state_definitions/function.adoc[function].

The `arguments` property defines the arguments that are to be passed to the referenced function. Here is an example of using the `arguments` property:

[source,json]
----
{
   "refName": "checkFundsAvailabe",
   "arguments": {
     "account": {
       "id": "${ .accountId }"
     },
     "forAmount": "${ .payment.amount }",
     "insufficientMessage": "The requested amount is not available."
   }
}
----

The `invoke` property defines how the function is invoked (sync or async). Default value of this property is `sync`, meaning that workflow execution should wait until the function completes. If set to `async`, workflow execution should just invoke the function and should not wait until its completion. Note that in this case the action does not produce any results and the associated actions actionDataFilter as well as its retry definition, if defined, should be ignored. In addition, functions that are invoked async do not propagate their errors to the associated action definition and the workflow state, meaning that any errors that happen during their execution cannot be handled in the workflow states onErrors definition. Note that errors raised during functions that are invoked async should not fail workflow execution.
